apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: dso202-assignment-01
data:
  DB_HOST: "database-service"
  DB_PORT: "5432"               
  DB_NAME: "app_db"
  APP_PORT: "8080"           # Port your backend API listens on
  CORS_ORIGIN: "http://localhost:8080" 
  POSTGRES_DB: "app_db"         
  BACKEND_URL: "http://localhost:5000" 
