apiVersion: v1
kind: ResourceQuota
metadata:
  name: app-resource-quota
  namespace: dso202-assignment-01
spec:
  hard:
    requests.cpu: "2"          # Total combined CPU requests allowed across all 3 tiers
    requests.memory: "2Gi"     # Total combined RAM requests allowed across all 3 tiers
    limits.cpu: "4"            # Absolute maximum CPU spike ceiling
    limits.memory: "4Gi"       # Absolute maximum RAM spike ceiling
    pods: "8"                 # Maximum number of concurrent pods allowed
