apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: dso202-assignment-01
type: Opaque
data:
  DB_USER: ZGJ1c2Vy               # "dbuser"
  DB_PASSWORD: ZGJwYXNzd29yZA==   # "dbpassword"
  POSTGRES_USER: ZGJ1c2Vy         # "dbuser"
  POSTGRES_PASSWORD: ZGJwYXNzd29yZA== # "dbpassword"
