# =============================================================================
# File        : deployment.yaml
# Practical   : DSO202 Practical 1 
# Apply with  : kubectl apply -f deployment.yaml
# Purpose     : Provisions a single-replica database pod using your custom image.
# =============================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deploy
  namespace: dso202-assignment-01
  labels:
    dso202/assignment: "01"
    dso202/managed-by: declarative
  annotations:
    dso202.cst.edu.bt/description: "Single-replica custom PostgreSQL database deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: database
  template:
    metadata:
      labels:
        tier: database
    spec:
      containers:
      - name: postgresql
        image: rynorbu11/dso202-db:1.0 # <-- Your custom data tier image
        imagePullPolicy: IfNotPresent     # Pulls from Docker Hub if missing, or uses local if loaded
        ports:
        - containerPort: 5432
          name: postgres-port
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
